### ISSUE TITLE
Install.sh didnt work for me

### ISSUE THREAD

**Issue by pauljt** [mozfreddyb/eslint-config-scanjs#1]
Probably an issue with mac. Also it ignores "n" as an option, and installs anyways lol. 

eslint-config-scanjs$ sudo ./install.sh
This will install eslint >=0.24.0 eslint-plugin-no-unsafe-innerhtml >=0.1.8 eslint-plugin-scanjs-rules >=0.1.3
Proceed? [Y/n] n
npm http GET https://registry.npmjs.org/eslint-plugin-no-unsafe-innerhtml
npm http GET https://registry.npmjs.org/eslint
npm http GET https://registry.npmjs.org/eslint-plugin-scanjs-rules
npm http GET https://registry.npmjs.org/%3E%3D0.1.8
npm http GET https://registry.npmjs.org/%3E%3D0.24.0
npm http GET https://registry.npmjs.org/%3E%3D0.1.3
npm http 304 https://registry.npmjs.org/eslint
npm http 404 https://registry.npmjs.org/%3E%3D0.24.0
....
(snipped)

**Comment by mozfreddyb** [comment]
>  Install.sh didnt work for me

Is this just about the Y/n prompt or did something else not work, @pauljt?

**Comment by pauljt** [comment]
Look at the repos its trying to get - something is wrong with the script and the treatment of >= etc

**Comment by mozfreddyb** [comment]
I don't have a mac to test, but I assume this is because sh != bash.

Can you try again with `sudo bash install.sh`?
In any case, I'll replace `#!/bin/sh` with `#!/bin/bash` in another commit.

**Comment by mozfreddyb** [comment]
Would this fix your problem, @pauljt?

**Comment by ruchna** [comment]
Same issue. Using bash didn't fix it.

> This will install eslint >=1.1.0 eslint-plugin-no-unsafe-innerhtml >=0.1.9 eslint-plugin-scanjs-rules >=0.1.3
> Proceed? [Y/n] y
> npm http GET https://registry.npmjs.org/eslint
> npm http GET https://registry.npmjs.org/eslint-plugin-no-unsafe-innerhtml
> npm http GET https://registry.npmjs.org/eslint-plugin-scanjs-rules
> npm http 200 https://registry.npmjs.org/eslint
> npm http 304 https://registry.npmjs.org/eslint-plugin-scanjs-rules
> npm http 304 https://registry.npmjs.org/eslint-plugin-no-unsafe-innerhtml
> npm http GET https://registry.npmjs.org/%3E%3D1.1.0
> npm http GET https://registry.npmjs.org/%3E%3D0.1.3
> npm http GET https://registry.npmjs.org/%3E%3D0.1.9
> npm http 404 https://registry.npmjs.org/%3E%3D0.1.3
> npm ERR! TypeError: Cannot read property 'latest' of undefined

**Comment by mozfreddyb** [comment]
Maybe this script is useless anyway?

I will rephrase the current installation & setup instructions as follows:

## Install
* npm -g install
* cp -v .eslintrc ~/.scanjs-eslintrc
## Use
cd project-to-scan/
eslint --no-eslintrc -c ~/.scanjs-eslintrc .
